# config file version
apiVersion: 1

# list of datasources to insert/update
# available in the database
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db:5050
    database: test
    user: monitor
    secureJsonData:
      password: 'password'
    jsonData:
      sslmode: 'disable'
      database: test